### ISSUE TITLE
PAGINA LOGIN

### ISSUE THREAD

**Issue by AaronPalomino2002** [AaronPalomino2002/USMPWEB#1]

**Comment by AaronPalomino2002** [comment]
![Image](https://github.com/user-attachments/assets/b1281f07-a269-4ee1-a6c7-23aa63f21ec9)

**Comment by Cetok** [comment]
![image](https://github.com/user-attachments/assets/21d8b2e0-145c-457e-9f16-3f24d49a44f0)
