### ISSUE TITLE
METODO DE PAGO

### ISSUE THREAD

**Issue by AaronPalomino2002** [AaronPalomino2002/USMPWEB#42]

**Comment by Cetok** [comment]
![image](https://github.com/user-attachments/assets/fe8456f0-cb72-4a29-8a70-1983d051d02a)

**Comment by Cetok** [comment]
![image](https://github.com/user-attachments/assets/2b81c31b-c7e5-4c12-9178-d9f5b1bee063)

**Comment by Cetok** [comment]
![image](https://github.com/user-attachments/assets/524e4b74-ef5f-464a-b886-b77f4a8b3e12)

**Comment by Cetok** [comment]
![image](https://github.com/user-attachments/assets/428cdad5-6257-42e2-b1c1-6800b7b66869)
